### ISSUE TITLE
TypeError: Received unknown keyword arguments: {'epochs': 400}

### ISSUE THREAD

**Issue by ekt1701** [jiexunsee/rudimentary-ai-composer#2]
Hello, when createmusic.py is run I get the following error:

`Traceback (most recent call last):
  File "createmusic.py", line 71, in <module>
    model.fit(X, Y, batch_size=300, epochs=400, verbose=1)
  File "/usr/local/lib/python2.7/site-packages/keras/models.py", line 661, in fit
    str(kwargs))
TypeError: Received unknown keyword arguments: {'epochs': 400}`

I have not made any changes to the code.

**Comment by jiexunsee** [comment]
I think the error might be because of the keras version you're using. Try `nb_epoch` instead of `epoch`, if I remember correctly it might work

**Comment by ekt1701** [comment]
Thank you, updating Keras fixed that error.  However, I got a blank midi after running the program.
After line 115 printed out the note data like this one, the program ended.

`[  1.47000000e+02   2.40000000e+01   0.00000000e+00   4.55250964e-02]`

When I print out  line 119 `track`, I get the following:

`<midi track u'' 1 messages>
<midi track u'' 2 messages>
<midi track u'' 3 messages>
<midi track u'' 4 messages>`

This pattern continued for 3000 messages.

Do you have any suggestions?

**Comment by jiexunsee** [comment]
Hmm, what was the error message? Anyways the program doesn't output any proper music for now, I'm still working on it!

**Comment by ekt1701** [comment]
There was no error message. When the program ended I had a file called new_song.mid, but it was blank, no midi data was written.

**Comment by jiexunsee** [comment]
I see. I'm not sure what is the problem :( I get the same output as you when I print track on line 119. However I do get a midi file that plays some random notes. Maybe try upping your volume? Because the created midi file is always very soft.

**Comment by ekt1701** [comment]
Turning up the volume does not make a difference.  I'll keep a watch on this repository.  I hope you have success in improving the output.
